### ISSUE TITLE
hmtai is available

### ISSUE THREAD

**Issue by BlueBerrySans365** [Nekidev/anime-api#30]
I don't know why you thought that Hmtai was taken down
Just use https://hmtai.hatsunia.cfd instead

**Comment by Nekidev** [comment]
yeah, I noticed right after pushing the version with that message. The API as using the heroku subdomain and that domain was taken down so that's why I thought that.

**Comment by BlueBerrySans365** [comment]
Oh, understandable, creator of hmtai just moved it on his own servers after news that heroku host is now not free.
