### ISSUE TITLE
A bit confused

### ISSUE THREAD

**Issue by lolpuud** [Nekidev/anime-api#40]
I noticed that in some sections, there was a misspelling of `objects`. It's not a big deal since you still handled that minor typo, but I also noticed that you were making API calls for `spoilerfication` and `owofication` of text. To be honest, that doesn't make much sense, as you can easily implement those features without relying on an external API.

```py
import random
import re

class TextManipulator:
    owo_replacements = {
        'r': 'w',
        'l': 'w',
        'R': 'W',
        'L': 'W',
        'n': 'ny',
        'N': 'Ny',
        'ove': 'uv',
        'you': 'u',
        'You': 'U',
        'th': 'f',
        'Th': 'F',
        'the': 'da',
        'The': 'Da',
    }

    def __init__(self, use_extra_emoticons=False):
        self.use_extra_emoticons = use_extra_emoticons
        self.extra_emoticons = [
            '(・`ω´・)', '(⁄ ⁄•⁄ω⁄•⁄ ⁄)', '(*≧ω≦)', '(´・ω・`)', '(¬‿¬)', '(´｡• ω •｡`)', '(*^ω^)',
            '（ ^_^）o自自o（^_^ ）', '＼(＾▽＾)／', '(*⌒▽⌒*)θ~♪', 'uwu', 'owo', 'UwU', 'OwO',
        ]

    def owofy_text(self, text):
        for key, value in self.owo_replacements.items():
            text = text.replace(key, value)

        if self.use_extra_emoticons:
            text += ' ' + random.choice(self.extra_emoticons)

        return text

    @staticmethod
    def has_special_chars(text):
        return bool(re.search(r'[!@#$%^&*(),.?":{}|<>]', text))

    @staticmethod
    def spoilerfy_text(text, spoiler_percentage=0.5):
        if 0 <= spoiler_percentage <= 1:
            spoiler_length = int(len(text) * spoiler_percentage)
            spoiler = '||' + text[:spoiler_length] + '||'
            return spoiler + text[spoiler_length:]
        else:
            return text

if __name__ == '__main__':
    text_manipulator = TextManipulator(use_extra_emoticons=False)
    
    input_text = input("Enter text to owofy: ")
    manipulated_text = text_manipulator.owofy_text(input_text)
    
    print("Owofied text: ", manipulated_text)
    
    spoiler_text = TextManipulator.spoilerfy_text(manipulated_text, spoiler_percentage=1)
    print("Spoilerfied text: ", spoiler_text)
```

**Comment by Nekidev** [comment]
Hi! This library contains API wrappers, not custom functionality, so although some features could be reimplemented, the idea of the library is to make API calls. That's why there is no local implementation of any features.

Regarding the typo, could you specify where you find it and/or create a PR to fix it? Thank you!

**Comment by lolpuud** [comment]
> Hi! This library contains API wrappers, not custom functionality, so although some features could be reimplemented, the idea of the library is to make API calls. That's why there are no local implementations of any features.
> 
> Regarding the typo, could you specify where you find it and/or create a PR to fix it? Thank you!

The typo is located in this directory: https://rip.is-hot.wtf/hot/40lMf.png
