### ISSUE TITLE
Studio Ghibli API is no longer available

### ISSUE THREAD

**Issue by RDKRACZ** [Nekidev/anime-api#44]
https://github.com/janaipakos/ghibliapi is dead since Heroku removed the free plan - "This repository has been archived by the owner on Dec 2, 2022. It is now read-only"
***
I have found some alternatives. Not sure if these are forks of the original projects or something completely different
https://ghibliapi.vercel.app/
https://ghibliapi.dev/
https://ghibli.rest/

**Comment by Nekidev** [comment]
Hello! I've updated the base endpoint to https://ghibliapi.dev/. I'll publish the new version on PyPi in a while.

You can (optionally) also pass a custom endpoint to it when initializing the wrapper doing:
```py
# No trailing slash
api = StudioGhibliAPI(endpoint="https://my.ghibli.endpoint")
```
